import Head from "next/head";
import React, { Children } from "react";
import style from "../styles/Layout.module.css";
import Footer from "./Footer";
import Navbar from "./Navbar";
import ShoppingCart from "./ShoppingCart";

const Layout = ({ children, title }) => {
  return (
    <div>
      <Head>
        <title>Rebel Store {title && `| ${title}`}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        
        
      </Head>

      <Navbar/>

      <div className={style.container}>{children}</div>
      <ShoppingCart/>
    </div>
  );
};

export default Layout;
